{% set name = "dydx-v4-client" %}
{% set version = "1.0.1" %}

# upstream repo only tags the JS version release (which includes the python client)
# This should help having regro PR updates, but will require manual inspection to
# verify the python client version number.
{% set repo_version = "1.3.7" %}
package:
  name: dydx-v4-client-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-clients/archive/refs/tags/v4-client-js@{{ repo_version }}.tar.gz
  sha256: 5ee96dc406286479610c0354ab99df81f80b8d7ee9367797b4d9f60a65cdc035
  patches:
    - patches/0001-use-pyext-over-_ubp.patch
    - patches/0002-upgrade-grpcio-dependency.patch

build:
  number: 1
  noarch: python

outputs:
  - name: dydx-v4-client
    script: install-py.sh
    build:
      noarch: python
    requirements:
      host:
        - dydxprotocol-v4-proto-py ==5.2.1
        - pip
        - poetry
        - python {{ python_min }}
        - typing-extensions ==4.12
      run:
        - dydxprotocol-v4-proto-py ==5.2.1
        - bech32 ==1.2
        - bip-utils ==2.9.3
        - ecdsa ==0.19
        - grpcio ==1.65.5
        - httpx ==0.27
        - pycryptodome ==3.20
        - python >={{ python_min }}
        - websocket-client ==1.7
    test:
      source_files:
        - v4-client-py-v2/pyproject.toml
        - v4-client-py-v2/tests
      imports:
        - dydx_v4_client
      requires:
        - pip
        - poetry
        - pytest
        - pytest-asyncio
        - pytest-dotenv
        - python {{ python_min }}
      commands:
        - pip check
        - cd v4-client-py-v2 && poetry run pytest || true

  # - PYPI naming conversion
  - name: dydx_v4_client
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('dydx-v4-client', exact=True) }}
    test:
      imports:
        - dydx_v4_client
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check

about:
  home: https://github.com/dydxprotocol/v4-clients
  summary: 'Python client for dYdX Chain. Developed and maintained by the Nethermind team.'
  description: |
    The dYdX v4 software (the ”dYdX Chain”) is a sovereign blockchain software built using
    Cosmos SDK and CometBFT. It powers a robust decentralized perpetual futures exchange
    with a high-performance orderbook and matching engine for a feature-rich, self-custodial
    perpetual trading experience on any market.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
  doc_url: https://docs.dydx.exchange/

extra:
  recipe-maintainers:
    - MementoRC
